FROM signoz/signoz-community:v0.110.2

COPY signoz/prometheus.yml /root/config/prometheus.yml
COPY dashboards /root/config/dashboards
COPY --chmod=755 entrypoint.sh /entrypoint.sh

HEALTHCHECK --interval=30s --timeout=10s --start-period=180s --retries=5 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:8080/api/v1/health || exit 1

ENTRYPOINT ["/entrypoint.sh"]
